[package]
name = "sbs_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json", "blocking"] }
# tokio = { version = "1", features = ["full"] }
tempfile = {version = "3.12"}
zip = {version = "2.2"}
clap = {version = "4.5", features= ["derive"]}
