import zipfile
import os
# from urllib.request import urlretrieve

#https://github.com/DizzyKungFu/Lucky_13/archive/refs/heads/main.zip
#https://github.com/DizzyKungFu/Lucky_13/archive/refs/heads/main.zip
#https://github.com/DizzyKungFu/Lucky_13/archive/refs/heads/main.zip
###curl
# "https://github.com/%USER%/%REPO%/zipball/%BRANCH%/"

def curlretrieve(url, localname):
    """Use curl to retrieve the files

    Args:
        url (str): the url
        localname (str): The local filename

    Returns:
        bool: True if the file was downloaded successfully, False otherwise.
    """
    import subprocess

    # Recommended way to run a command and capture output
    try:
        # -f/--fail makes curl exit non-zero on HTTP errors (e.g. 404) instead
        # of quietly writing the error page (like GitHub's 404 HTML) to disk.
        result = subprocess.run(
            ["curl", "-f", "-L", "--max-redirs", "5", f"{url}", "--output", localname],  # Command and arguments as a list
            capture_output=True,   # Capture stdout and stderr
            text=True,             # Return strings instead of bytes
            check=True             # Raise exception on non-zero exit
        )
        print("Command ran successfully.")
        print(result.stdout)
        return True
    except subprocess.CalledProcessError as e:
        print(f"Command failed with return code {e.returncode}")
        print(e.stderr)
        return False
    except FileNotFoundError:
        print("Command not found.")
        return False


# DERIVED ART IS NEVER PACKAGED, and this is not a size optimization.
#
# A `.paxmesh` BAKES THE FOLDER IT WAS CREATED IN. Its texture references are stored as
# paths ("ships/<name>_diffuse", or an exe-relative pack path), so a mesh baked in one
# folder looks for its textures relative to THAT folder wherever it later ends up. Ship
# one inside a media pack and it points at somebody else's disk: the engine resolves the
# textures to nothing and dereferences NULL in DX11PAXShaderRedwood::Draw3DMesh - a
# crash-to-desktop, not a missing texture.
#
# It has to be created where `artfileroot` points, by the engine, on the machine that
# runs it. Cosmos-TNG-Mod shipped 45 of them in its media pack for exactly this reason:
# a mod's .gitignore already excluded them, but the packer walked the folder and took
# them anyway, so "not in git" never meant "not in the zip" (2026-08-21).
_DERIVED_EXT = (".paxmesh", ".pointcube", ".rawbitmap")
_DERIVED_PNG = ("1024.png", "256.png")


def is_derived_art(root, file):
    """Is this file generated by the engine from art that ships beside it?

    The three extensions are only ever engine output, so they go unconditionally. The
    `<name>1024.png` / `<name>256.png` thumbnails are judged by whether the MESH they
    were generated from is sitting next to them - a mission is free to ship art of its
    own that happens to end in "1024", and guessing on the name alone would drop it.
    """
    low = file.lower()
    if low.endswith(_DERIVED_EXT):
        return True
    for suffix in _DERIVED_PNG:
        if low.endswith(suffix):
            base = file[: -len(suffix)]
            for ext in (".obj", ".paxmesh"):
                if os.path.exists(os.path.join(root, base + ext)):
                    return True
    return False


# WHAT A COMPLETE BAKE LOOKS LIKE, and this is MEASURED off the stock corpus rather than
# assumed - 201 art roots in data/graphics/ships produce exactly three combinations:
#
#   paxmesh + 1024 + 256, no pointcube   120 roots   healthy
#   paxmesh + pointcube + 1024 + 256      64 roots   healthy
#   nothing at all                        17 roots   never drawn
#
# So the three that always travel together are `.paxmesh`, `<root>1024.png` and
# `<root>256.png`. `.pointcube` is OPTIONAL - 120 healthy roots (asteroids, containers,
# mines, the primitives) have none, and requiring it flags every one of them. `.rawbitmap`
# has never been observed being generated at all. Both stay in _DERIVED_EXT because they
# are unmistakably engine output when they DO turn up and must not be packaged; they just
# are not evidence of a finished bake.
#
# See VisualTestRange/ENGINE_BUG_derived_art_generation.md for what the engine writes and
# where. Note that doc records `.pointcube` as generated beside the art, which is true but
# not universal - the corpus above is the authority on what to REQUIRE.
_BAKE_REQUIRED = (".paxmesh", "1024.png", "256.png")
_BAKE_OPTIONAL = (".pointcube", ".rawbitmap")

# THE SPRITES ARE A SHIP THING, and this is measured too. Walking a stock `data/graphics`:
#
#   graphics/ships/   184 paxmesh+sprites   0 paxmesh-without-sprites   17 undrawn
#   graphics/ (root)    0 paxmesh+sprites   9 paxmesh-without-sprites    3 undrawn
#
# Not one counterexample either way. The flat `<root>1024.png` is what a hull is drawn AS
# when something needs it face-on - the called-shot panel, the interior mask - and the
# effect meshes at the graphics root (typhon parts, drones, AHBall, oldClassicMonsterPart)
# are only ever 3D, so the engine never makes them one. Requiring sprites everywhere
# reports those 9 as broken on a clean install, which is how a check earns its way into
# being ignored.
_SPRITE_FOLDERS = ("ships",)

# The source meshes a bake is derived FROM. A root is only interesting if one of these is
# sitting there - otherwise a stray `foo256.png` would invent an art root that never was.
_SOURCE_EXT = (".obj",)


def derived_art_status(folder):
    """Per art root in `folder`, what the engine has and has not baked.

    THE STATE THAT MATTERS IS "half". A root with the complete set renders. A root with
    NOTHING derived is simply art nobody has drawn yet, which is normal and must not be
    reported as broken. A root with SOME of the set is the one that crashes the client, on
    every draw, forever: the engine retries the bake, dies at the same point, and leaves the
    same partial output behind. Three hulls were in that state and cost two separate crash
    investigations before anyone looked at the folder.

    Returns:
        dict: root name -> {"present": [...], "absent": [...], "state": one of
            "complete" | "unbaked" | "half"}. Roots with no source mesh are skipped, and
            the optional members are reported but never make a root "half".
    """
    out = {}
    try:
        names = os.listdir(folder)
    except OSError:
        return out
    have = {n.lower() for n in names}
    roots = sorted({n[: -len(ext)] for n in names for ext in _SOURCE_EXT
                    if n.lower().endswith(ext)})
    wants_sprites = os.path.basename(os.path.normpath(folder)).lower() in _SPRITE_FOLDERS
    required = _BAKE_REQUIRED if wants_sprites else (".paxmesh",)
    for root in roots:
        low = root.lower()
        present = [m for m in required if low + m in have]
        absent = [m for m in required if low + m not in have]
        extra = [m for m in _BAKE_OPTIONAL if low + m in have]
        if not absent:
            state = "complete"
        elif not present:
            state = "unbaked"
        else:
            state = "half"
        out[root] = {"present": present + extra, "absent": absent, "state": state}
    return out


def derived_art_files(folder, root):
    """Every derived file belonging to `root`, for deleting it.

    Deliberately wider than what :func:`derived_art_status` REQUIRES: clearing a half-baked
    root has to take `.rawbitmap` with it too, or a re-bake starts from a folder that is
    still partly stale.
    """
    out = []
    low = root.lower()
    try:
        names = os.listdir(folder)
    except OSError:
        return out
    for n in names:
        nl = n.lower()
        if not nl.startswith(low):
            continue
        if nl.endswith(_DERIVED_EXT) and nl[: -len(os.path.splitext(nl)[1])] == low:
            out.append(n)
            continue
        for png in _DERIVED_PNG:
            if nl.endswith(png) and nl[: -len(png)] == low:
                out.append(n)
    return sorted(out)


def zipdir(folder_path, zip_file_name, first_folder=None):

    skips =  {"__pycache__"}
    dropped = []
    #
    with zipfile.ZipFile(zip_file_name, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=8) as zf:
        for root, subdirs, files in os.walk(folder_path):
            s = False
            for skip in skips:
                if skip in root:
                    s = True
            if s:
                continue

            for file in files:
                file_path = os.path.join(root, file)

                # Engine-generated art never ships - see is_derived_art. A .paxmesh carries
                # the folder it was baked in, so packaging one hands every install a mesh
                # that looks for its textures somewhere they are not.
                if is_derived_art(root, file):
                    dropped.append(os.path.relpath(file_path, folder_path))
                    continue

                archive_path = str(os.path.relpath(file_path, folder_path))

                if first_folder is not None:
                    archive_path = f"{first_folder}\\{archive_path}"
                zf.write(file_path, archive_path)

    # SAY SO. A packer that quietly drops files is indistinguishable from one that is
    # broken, and this one drops art the author may believe they are shipping.
    if dropped:
        print(f"  derived art not packaged ({len(dropped)} file(s)) - the engine rebuilds "
              f"these where artfileroot points: "
              + ", ".join(sorted(dropped)[:3]) + (" ..." if len(dropped) > 3 else ""))
    return dropped


def unzip_exclude(zip_path, extract_dir, exclude_files=None):
    """
    Unzips a file, excluding specified files from extraction.

    Args:
        zip_path (str): The path to the zip file.
        extract_dir (str): The directory where files should be extracted.
        exclude_files (list, optional): A list of filenames (or patterns) to exclude.
                                        Defaults to None, meaning no files are excluded.
    """
    if exclude_files is None:
        exclude_files = []

    os.makedirs(extract_dir, exist_ok=True)
    #
    # This unzips removing the github folder
    #
    with zipfile.ZipFile(zip_path, 'r') as zf:
        for member in zf.infolist():
            parts = member.filename.split('/')
            # Check if the member should be excluded
            if any(exclude_pattern in member.filename for exclude_pattern in exclude_files):
                #print(f"Skipping excluded file: {member}")
                continue

            # Extract the member if it's not excluded
            # Handle directories separately to ensure they are created
            # If there's a top-level directory and it's not a directory entry itself
            if len(parts) > 1 and not member.filename.endswith('/'):
                # Reconstruct the filename, skipping the first part
                new_filename = os.sep.join(parts[1:])
                
                # Only proceed if there's a valid new filename (not just an empty string)
                if new_filename:
                    # Create the full path for the extracted file
                    target_path = os.path.join(extract_dir, new_filename)
                    
                    # Create parent directories if they don't exist
                    os.makedirs(os.path.dirname(target_path), exist_ok=True)
                    
                    # Extract the file with the modified name
                    with open(target_path, 'wb') as f:
                        f.write(zf.read(member.filename))
            elif not member.filename.endswith('/'): # Handle files directly in the root of the zip
                target_path = os.path.join(extract_dir, member.filename)
                os.makedirs(os.path.dirname(target_path), exist_ok=True)
                with open(target_path, 'wb') as f:
                    f.write(zf.read(member.filename))



def unzip_subpath(zip_path, extract_dir, subpath=None, exclude_files=None):
    """Extract ONE folder out of a GitHub archive, as if it were the whole repo.

    `unzip_exclude` strips the archive's single root folder (`repo-branch/`) and lays the
    rest down flat. A template repo needs one more strip: `templates/amd/story.mast` has to
    land as `story.mast`, or every created mission would carry the template's own scaffolding
    path. Passing `subpath=None` (or ".") behaves like `unzip_exclude` - the whole repo.

    Args:
        zip_path (str): The downloaded archive.
        extract_dir (str): Where the files should land.
        subpath (str, optional): Folder INSIDE the repo to treat as the root.
        exclude_files (list, optional): Substrings; a member matching any is skipped. Matched
            against the path AFTER both strips, so callers write repo-relative patterns.

    Returns:
        int: How many files were written. Zero means the subpath does not exist in that
            archive - a caller must treat it as a failure rather than leaving an empty
            mission folder behind.
    """
    if exclude_files is None:
        exclude_files = []

    sub = (subpath or "").strip().replace("\\", "/").strip("/")
    if sub == ".":
        sub = ""
    prefix = f"{sub}/" if sub else ""

    written = 0
    with zipfile.ZipFile(zip_path, 'r') as zf:
        for member in zf.infolist():
            if member.filename.endswith('/'):
                continue
            parts = member.filename.split('/')
            if len(parts) < 2:
                # A GitHub archive always wraps everything in `repo-branch/`; a member with
                # no folder is not ours to place.
                continue
            rel = "/".join(parts[1:])
            if prefix:
                if not rel.startswith(prefix):
                    continue
                rel = rel[len(prefix):]
            if not rel:
                continue
            if any(pattern in rel for pattern in exclude_files):
                continue
            target_path = os.path.join(extract_dir, *rel.split("/"))
            parent = os.path.dirname(target_path)
            if parent:
                os.makedirs(parent, exist_ok=True)
            with open(target_path, 'wb') as f:
                f.write(zf.read(member.filename))
            written += 1
    return written


def release_asset_candidates(local_name):
    """The names to try on a GitHub release for a lib whose LOCAL name is `local_name`.

    A lib is stored in `__lib__/` (and referenced from story.json) as
    `{user}.{repo}.{folder}.{version}.{ext}`, but repos do not all PUBLISH it under that
    name. sbs_utils' workflow interpolates owner+repo, so its sbslib asset matches the
    local name; LegendaryMissions' workflow interpolates only the bare folder, so
    `artemis-sbs.LegendaryMissions.hangar.v1.4.0.mastlib` is published as
    `hangar.v1.4.0.mastlib`. Both conventions are live and neither is going away.

    Returns a LIST, most likely first, so a caller can fall back rather than 404 and give
    up: the two repos already disagree and either could change, and the fallback costs one
    extra request only when the first name misses.

    Args:
        local_name (str): The lib's filename as stored in `__lib__/`.

    Returns:
        list[str]: Asset names to try, or `[local_name]` if the name cannot be parsed.
    """
    if local_name.endswith(".sbslib"):
        # {user}.{package}.{version}.sbslib - only TWO segments precede the version, and
        # the asset is published under exactly this name. Stripping them would leave a
        # bare "v1.4.0.sbslib", so there is no meaningful alternative to offer.
        return [local_name]
    parts = local_name.split(".", 2)          # {user}.{repo}.{folder}.{version}.{ext}
    if len(parts) != 3:
        return [local_name]
    # Canonical name first: the repo now publishes mastlibs under the same name they are
    # stored as. The bare `{folder}.{version}.{ext}` form is what LegendaryMissions used
    # to publish, kept as a fallback so an older tag still resolves.
    return [local_name, parts[2]]


def fetch_deps(dep_libs, is_sbs_lib, overwrite_libs):
    """ This will fetch the dependencies from a github release

    Args:
        dep_libs ([str]]): The list of dependencies
        is_sbs_lib (bool): If this is a list of sbslibs they have different naming conventions

    Returns:
        list[str]: The dependencies that could NOT be fetched. A caller that ignores this
            reports success for a mission whose libraries never arrived, which is how a
            missing dependency became a printed line in a wall of output rather than a
            failure.
    """
    failed = []
    for dep_lib in dep_libs:
        parts = dep_lib.split(".", 2)
        #print(parts)
        if len(parts) != 3:
            print(f"ERROR: unsupported dependency format {dep_lib}")
            failed.append(dep_lib)
            continue
        user = parts[0]
        repo = parts[1]
        file = parts[2]
        
        version = file.split(".")
        if len(version) < 3:
            print(f"ERROR: unsupported dependency format {dep_lib}")
            failed.append(dep_lib)
            continue
        # remove front
        if not is_sbs_lib:
            version = version[1:]
        # remove end
        version = version[:-1]
        # put back
        version = ".".join(version)

        target = f"__lib__/{dep_lib}"
        if not overwrite_libs and os.path.exists(target):
            #print("SKIPPING")
            continue
        
        os.makedirs("__lib__", exist_ok=True)
        base = f"https://github.com/{user}/{repo}/releases/download/{version}"
        # Stage through a temp file and only accept a real archive. `curl -f` still CREATES
        # the output file on a 404, and an empty (or HTML) lib left at `target` is silently
        # skipped by the exists() check above on the next run - a corrupt lib that looks
        # fetched. Every dependency here is a zip (.sbslib/.mastlib/.zip), so is_zipfile is
        # the same check the `sbs debug` fetch path already made.
        tmp = target + ".download"
        errors = []
        for asset in release_asset_candidates(dep_lib):
            url = f"{base}/{asset}"
            print(f"Fetching {dep_lib} from {url} to {target}")
            try:
                curlretrieve(url, tmp)
            except Exception as e:
                errors.append(f"{asset}: {e}")
                continue
            if os.path.isfile(tmp) and zipfile.is_zipfile(tmp):
                os.replace(tmp, target)
                break
            errors.append(f"{asset}: not a valid archive")
        else:
            failed.append(dep_lib)
            for e in errors:
                print(f"ERROR: Fetching {dep_lib}\n{e}")
        if os.path.exists(tmp):
            os.remove(tmp)
    return failed

#https://github.com/artemis-sbs/sbs_utils/releases/download/v1.3.0/artemis-sbs.v1.3.0.sbslib
#https://github.com/artemis-sbs/LegendaryMissions/releases/download/v1.3.0/basic_player_destroy.v1.3.0.mastlib 