name: Create Archive
on: 
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set env version
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
  
    - name: Build
      run: python3 dev.pyz build --install


    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist\\sbs.pyz,bat\\sbs.bat"
        token: ${{ secrets.GITHUB_TOKEN }}

